name: Deploy Frontend to Firebase Preview Channel

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'task/**'
    paths:
      - 'client/**'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'client/**'

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: 'client/package-lock.json'
      
      - name: Install Dependencies
        run: |
          cd client
          npm ci || npm install
      
      - name: Build Frontend
        run: |
          cd client
          CI=false npm run build
      
      - name: Deploy to Firebase Preview Channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: project-reciept-reader-id
          channelId: preview-${{ github.ref_name }}-${{ github.sha }}
          expires: 14d
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
