# File: .github/workflows/test-security-rules.yml
# Date: 2025-05-17 04:54:05
# Description: CI/CD workflow to automatically test Firebase security rules on push and pull requests.
# Reasoning: Ensures that changes to security rules or related test files are validated before merging.

name: Test Firebase Security Rules

on:
  push:
    branches: [ main ]
    paths:
      - 'firestore.rules'
      - 'storage.rules'
      - 'server/tests/security/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'firestore.rules'
      - 'storage.rules'
      - 'server/tests/security/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    
    - name: Install dependencies
      run: |
        npm ci
        cd server
        npm ci
    
    - name: Install Firebase tools
      run: npm install -g firebase-tools
    
    - name: Run security rules tests with emulator
      run: |
        firebase emulators:exec --only firestore,storage "cd server && npm test tests/security"
